### ISSUE TITLE
deface issue, when I tried to install this extension..

### ISSUE THREAD

**Issue by calebyk** [spree/spree_multi_vendor#214]
I am trying to install this extension on my spree app.
the error is this after the command.

anyone can help me?

 ------  error --
bundle exec rails g spree_multi_vendor:install

[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
/home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/override.rb:70:in `initialize': :action is invalid (ArgumentError)
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/dsl/context.rb:15:in `new'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/dsl/context.rb:15:in `create_override'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/dsl/loader.rb:56:in `build_context_and_extract_dsl_from'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/dsl/loader.rb:37:in `build_erb_context'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/dsl/loader.rb:27:in `build_context'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/dsl/loader.rb:22:in `block in load'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/dsl/loader.rb:17:in `open'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/dsl/loader.rb:17:in `load'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/environment.rb:94:in `block (2 levels) in enumerate_and_load'
        from <internal:dir>:134:in `glob'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/environment.rb:93:in `block in enumerate_and_load'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/environment.rb:85:in `each'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/environment.rb:85:in `enumerate_and_load'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/environment.rb:79:in `load_overrides'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/environment.rb:62:in `block in load_all'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/environment.rb:60:in `each'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/environment.rb:60:in `load_all'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/deface-1.9.0/lib/deface/railtie.rb:12:in `activate'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
        from /home/touchu/com.itamina/config/environment.rb:5:in `<main>'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/application.rb:367:in `require_environment!'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/command/actions.rb:28:in `require_environment!'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/command/base.rb:69:in `perform'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/command.rb:48:in `invoke'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/commands.rb:18:in `<main>'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/touchu/com.itamina/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'

**Comment by calebyk** [comment]
it was my personal environment issue..
sorry for fuss..
